# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: blog.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\nblog.proto\x12\x04\x62log\"E\n\x04\x42log\x12\n\n\x02id\x18\x01 \x01(\t\x12\x11\n\tauthor_id\x18\x02 \x01(\t\x12\r\n\x05title\x18\x03 \x01(\t\x12\x0f\n\x07\x63ontent\x18\x04 \x01(\t\")\n\rCreateBlogReq\x12\x18\n\x04\x62log\x18\x01 \x01(\x0b\x32\n.blog.Blog\")\n\rCreateBlogRes\x12\x18\n\x04\x62log\x18\x01 \x01(\x0b\x32\n.blog.Blog\")\n\rUpdateBlogReq\x12\x18\n\x04\x62log\x18\x01 \x01(\x0b\x32\n.blog.Blog\")\n\rUpdateBlogRes\x12\x18\n\x04\x62log\x18\x01 \x01(\x0b\x32\n.blog.Blog\"\x19\n\x0bReadBlogReq\x12\n\n\x02id\x18\x01 \x01(\t\"\'\n\x0bReadBlogRes\x12\x18\n\x04\x62log\x18\x01 \x01(\x0b\x32\n.blog.Blog\"\x1b\n\rDeleteBlogReq\x12\n\n\x02id\x18\x01 \x01(\t\" \n\rDeleteBlogRes\x12\x0f\n\x07success\x18\x01 \x01(\x08\"\x12\n\x10ListBlogsRequest\"-\n\x11ListBlogsResponse\x12\x18\n\x04\x62log\x18\x01 \x01(\x0b\x32\n.blog.Blog2\xa7\x02\n\x0b\x42logService\x12\x36\n\nCreateBlog\x12\x13.blog.CreateBlogReq\x1a\x13.blog.CreateBlogRes\x12\x30\n\x08ReadBlog\x12\x11.blog.ReadBlogReq\x1a\x11.blog.ReadBlogRes\x12\x36\n\nUpdateBlog\x12\x13.blog.UpdateBlogReq\x1a\x13.blog.UpdateBlogRes\x12\x36\n\nDeleteBlog\x12\x13.blog.DeleteBlogReq\x1a\x13.blog.DeleteBlogRes\x12>\n\tListBlogs\x12\x16.blog.ListBlogsRequest\x1a\x17.blog.ListBlogsResponse0\x01\x42\x08Z\x06\x62logpbb\x06proto3')



_BLOG = DESCRIPTOR.message_types_by_name['Blog']
_CREATEBLOGREQ = DESCRIPTOR.message_types_by_name['CreateBlogReq']
_CREATEBLOGRES = DESCRIPTOR.message_types_by_name['CreateBlogRes']
_UPDATEBLOGREQ = DESCRIPTOR.message_types_by_name['UpdateBlogReq']
_UPDATEBLOGRES = DESCRIPTOR.message_types_by_name['UpdateBlogRes']
_READBLOGREQ = DESCRIPTOR.message_types_by_name['ReadBlogReq']
_READBLOGRES = DESCRIPTOR.message_types_by_name['ReadBlogRes']
_DELETEBLOGREQ = DESCRIPTOR.message_types_by_name['DeleteBlogReq']
_DELETEBLOGRES = DESCRIPTOR.message_types_by_name['DeleteBlogRes']
_LISTBLOGSREQUEST = DESCRIPTOR.message_types_by_name['ListBlogsRequest']
_LISTBLOGSRESPONSE = DESCRIPTOR.message_types_by_name['ListBlogsResponse']
Blog = _reflection.GeneratedProtocolMessageType('Blog', (_message.Message,), {
  'DESCRIPTOR' : _BLOG,
  '__module__' : 'blog_pb2'
  # @@protoc_insertion_point(class_scope:blog.Blog)
  })
_sym_db.RegisterMessage(Blog)

CreateBlogReq = _reflection.GeneratedProtocolMessageType('CreateBlogReq', (_message.Message,), {
  'DESCRIPTOR' : _CREATEBLOGREQ,
  '__module__' : 'blog_pb2'
  # @@protoc_insertion_point(class_scope:blog.CreateBlogReq)
  })
_sym_db.RegisterMessage(CreateBlogReq)

CreateBlogRes = _reflection.GeneratedProtocolMessageType('CreateBlogRes', (_message.Message,), {
  'DESCRIPTOR' : _CREATEBLOGRES,
  '__module__' : 'blog_pb2'
  # @@protoc_insertion_point(class_scope:blog.CreateBlogRes)
  })
_sym_db.RegisterMessage(CreateBlogRes)

UpdateBlogReq = _reflection.GeneratedProtocolMessageType('UpdateBlogReq', (_message.Message,), {
  'DESCRIPTOR' : _UPDATEBLOGREQ,
  '__module__' : 'blog_pb2'
  # @@protoc_insertion_point(class_scope:blog.UpdateBlogReq)
  })
_sym_db.RegisterMessage(UpdateBlogReq)

UpdateBlogRes = _reflection.GeneratedProtocolMessageType('UpdateBlogRes', (_message.Message,), {
  'DESCRIPTOR' : _UPDATEBLOGRES,
  '__module__' : 'blog_pb2'
  # @@protoc_insertion_point(class_scope:blog.UpdateBlogRes)
  })
_sym_db.RegisterMessage(UpdateBlogRes)

ReadBlogReq = _reflection.GeneratedProtocolMessageType('ReadBlogReq', (_message.Message,), {
  'DESCRIPTOR' : _READBLOGREQ,
  '__module__' : 'blog_pb2'
  # @@protoc_insertion_point(class_scope:blog.ReadBlogReq)
  })
_sym_db.RegisterMessage(ReadBlogReq)

ReadBlogRes = _reflection.GeneratedProtocolMessageType('ReadBlogRes', (_message.Message,), {
  'DESCRIPTOR' : _READBLOGRES,
  '__module__' : 'blog_pb2'
  # @@protoc_insertion_point(class_scope:blog.ReadBlogRes)
  })
_sym_db.RegisterMessage(ReadBlogRes)

DeleteBlogReq = _reflection.GeneratedProtocolMessageType('DeleteBlogReq', (_message.Message,), {
  'DESCRIPTOR' : _DELETEBLOGREQ,
  '__module__' : 'blog_pb2'
  # @@protoc_insertion_point(class_scope:blog.DeleteBlogReq)
  })
_sym_db.RegisterMessage(DeleteBlogReq)

DeleteBlogRes = _reflection.GeneratedProtocolMessageType('DeleteBlogRes', (_message.Message,), {
  'DESCRIPTOR' : _DELETEBLOGRES,
  '__module__' : 'blog_pb2'
  # @@protoc_insertion_point(class_scope:blog.DeleteBlogRes)
  })
_sym_db.RegisterMessage(DeleteBlogRes)

ListBlogsRequest = _reflection.GeneratedProtocolMessageType('ListBlogsRequest', (_message.Message,), {
  'DESCRIPTOR' : _LISTBLOGSREQUEST,
  '__module__' : 'blog_pb2'
  # @@protoc_insertion_point(class_scope:blog.ListBlogsRequest)
  })
_sym_db.RegisterMessage(ListBlogsRequest)

ListBlogsResponse = _reflection.GeneratedProtocolMessageType('ListBlogsResponse', (_message.Message,), {
  'DESCRIPTOR' : _LISTBLOGSRESPONSE,
  '__module__' : 'blog_pb2'
  # @@protoc_insertion_point(class_scope:blog.ListBlogsResponse)
  })
_sym_db.RegisterMessage(ListBlogsResponse)

_BLOGSERVICE = DESCRIPTOR.services_by_name['BlogService']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'Z\006blogpb'
  _BLOG._serialized_start=20
  _BLOG._serialized_end=89
  _CREATEBLOGREQ._serialized_start=91
  _CREATEBLOGREQ._serialized_end=132
  _CREATEBLOGRES._serialized_start=134
  _CREATEBLOGRES._serialized_end=175
  _UPDATEBLOGREQ._serialized_start=177
  _UPDATEBLOGREQ._serialized_end=218
  _UPDATEBLOGRES._serialized_start=220
  _UPDATEBLOGRES._serialized_end=261
  _READBLOGREQ._serialized_start=263
  _READBLOGREQ._serialized_end=288
  _READBLOGRES._serialized_start=290
  _READBLOGRES._serialized_end=329
  _DELETEBLOGREQ._serialized_start=331
  _DELETEBLOGREQ._serialized_end=358
  _DELETEBLOGRES._serialized_start=360
  _DELETEBLOGRES._serialized_end=392
  _LISTBLOGSREQUEST._serialized_start=394
  _LISTBLOGSREQUEST._serialized_end=412
  _LISTBLOGSRESPONSE._serialized_start=414
  _LISTBLOGSRESPONSE._serialized_end=459
  _BLOGSERVICE._serialized_start=462
  _BLOGSERVICE._serialized_end=757
# @@protoc_insertion_point(module_scope)
