# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import blog_pb2 as blog__pb2


class BlogServiceStub(object):
    """services
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.CreateBlog = channel.unary_unary(
                '/blog.BlogService/CreateBlog',
                request_serializer=blog__pb2.CreateBlogReq.SerializeToString,
                response_deserializer=blog__pb2.CreateBlogRes.FromString,
                )
        self.ReadBlog = channel.unary_unary(
                '/blog.BlogService/ReadBlog',
                request_serializer=blog__pb2.ReadBlogReq.SerializeToString,
                response_deserializer=blog__pb2.ReadBlogRes.FromString,
                )
        self.UpdateBlog = channel.unary_unary(
                '/blog.BlogService/UpdateBlog',
                request_serializer=blog__pb2.UpdateBlogReq.SerializeToString,
                response_deserializer=blog__pb2.UpdateBlogRes.FromString,
                )
        self.DeleteBlog = channel.unary_unary(
                '/blog.BlogService/DeleteBlog',
                request_serializer=blog__pb2.DeleteBlogReq.SerializeToString,
                response_deserializer=blog__pb2.DeleteBlogRes.FromString,
                )
        self.ListBlogs = channel.unary_stream(
                '/blog.BlogService/ListBlogs',
                request_serializer=blog__pb2.ListBlogsRequest.SerializeToString,
                response_deserializer=blog__pb2.ListBlogsResponse.FromString,
                )


class BlogServiceServicer(object):
    """services
    """

    def CreateBlog(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ReadBlog(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateBlog(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteBlog(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListBlogs(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_BlogServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'CreateBlog': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateBlog,
                    request_deserializer=blog__pb2.CreateBlogReq.FromString,
                    response_serializer=blog__pb2.CreateBlogRes.SerializeToString,
            ),
            'ReadBlog': grpc.unary_unary_rpc_method_handler(
                    servicer.ReadBlog,
                    request_deserializer=blog__pb2.ReadBlogReq.FromString,
                    response_serializer=blog__pb2.ReadBlogRes.SerializeToString,
            ),
            'UpdateBlog': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateBlog,
                    request_deserializer=blog__pb2.UpdateBlogReq.FromString,
                    response_serializer=blog__pb2.UpdateBlogRes.SerializeToString,
            ),
            'DeleteBlog': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteBlog,
                    request_deserializer=blog__pb2.DeleteBlogReq.FromString,
                    response_serializer=blog__pb2.DeleteBlogRes.SerializeToString,
            ),
            'ListBlogs': grpc.unary_stream_rpc_method_handler(
                    servicer.ListBlogs,
                    request_deserializer=blog__pb2.ListBlogsRequest.FromString,
                    response_serializer=blog__pb2.ListBlogsResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'blog.BlogService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class BlogService(object):
    """services
    """

    @staticmethod
    def CreateBlog(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/blog.BlogService/CreateBlog',
            blog__pb2.CreateBlogReq.SerializeToString,
            blog__pb2.CreateBlogRes.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def ReadBlog(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/blog.BlogService/ReadBlog',
            blog__pb2.ReadBlogReq.SerializeToString,
            blog__pb2.ReadBlogRes.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def UpdateBlog(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/blog.BlogService/UpdateBlog',
            blog__pb2.UpdateBlogReq.SerializeToString,
            blog__pb2.UpdateBlogRes.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def DeleteBlog(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/blog.BlogService/DeleteBlog',
            blog__pb2.DeleteBlogReq.SerializeToString,
            blog__pb2.DeleteBlogRes.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def ListBlogs(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(request, target, '/blog.BlogService/ListBlogs',
            blog__pb2.ListBlogsRequest.SerializeToString,
            blog__pb2.ListBlogsResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
